# Generated by Django 4.2.7 on 2023-11-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_game', models.CharField(max_length=100, null=True)),
                ('time_title', models.TimeField()),
                ('hall', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GamePostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Enter your game name')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='games/')),
                ('cost', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Simulator', 'Simulator'), ('Quest', 'Quest')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Enter your title')),
                ('description', models.TextField(verbose_name='Enter your description')),
            ],
            options={
                'verbose_name': 'Бегущую строку',
                'verbose_name_plural': 'Бегущие строки',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
            ],
        ),
    ]
